# Generated by Django 5.1.4 on 2025-01-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_remove_comment_replay_replaycomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaycomment',
            name='user',
        ),
        migrations.AddField(
            model_name='replaycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replayed_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
