# Generated by Django 5.1.4 on 2025-01-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0007_alter_profiledata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaycomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replaycomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
