# Generated by Django 5.1.4 on 2025-01-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0008_replaycomment_created_at_replaycomment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaycomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='replaycomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ReplayComment',
        ),
    ]
