# Generated by Django 5.1.4 on 2025-01-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0002_alter_comment_post'),
        ('profileApp', '0009_remove_replaycomment_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
