# Generated by Django 5.1.4 on 2025-01-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
