# Generated by Django 5.1.4 on 2025-01-29 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0001_initial'),
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comment', to='postApp.posts'),
        ),
    ]
